# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 097e0426fc0dbe1cdb122193db798830399bff0f4aa4dd529e577b5909c68a2348fd01f34c72d49dc72a4fc5563f5a467521020259c6ab741d17d156b5e90ee6

test:
  secret_key_base: b5e4660473c9e3912aded1ce3bab99db08357647ae9f76a4e12e8d06db445526df82d663a1e73864910dcb18374e15b461d0bfd0570c6a39a300f2867769714e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
